version: '3.8'

services:
  telegram-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/data  # сохраняет bot_state.json между перезапусками
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"